{% set version = "0.5.0" %}

package:
  name: layla
  version: {{ version }}

source:
  url: dist/layla-{{ version }}-cp36-cp36m-win_amd64.whl


requirements:
  host:
    - python=3.6
    - pip
  run:
    - python=3.6
    - importlib_resources>=1.0.2

test:
  imports:
    - layla

about:
  home: https://github.com/vineetbansal/layla
  license: MIT
  summary: 'Boilerplate for a starter Python package'
  description: |
    Boilerplate for a starter Python package meant to go on PyPI or Anaconda Cloud
