{% set version = "0.1.4" %}

package:
  name: layla
  version: {{ version }}

source:
  url: dist/layla-{{ version }}.tar.gz

build:
  noarch: python
  number: 0
  script:
    - python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
  run:
    - python
    - importlib_resources>=1.0.2

test:
  imports:
    - layla

about:
  home: https://github.com/vineetbansal/layla
  license: MIT
  summary: 'Boilerplate for a starter Python package'
  description: |
    Boilerplate for a starter Python package meant to go on PyPI or Anaconda Cloud
